### ISSUE TITLE
Subject: profiles stage AES-CBC output produces unaligned ciphertext (not multiple of block size)

### ISSUE THREAD

**Issue by tomaszniezbedny** [BishopFox/sliver#1981]
Hi,

I'm encountering a decryption issue with AES-encrypted payloads generated using the profiles stage command in Sliver (latest version). The payloads cannot be decrypted using AES-CBC with padding disabled, as the ciphertext length is not a multiple of 16 bytes.

Working command (Sliver v1.5.43, stage-listener):
stage-listener --url http://x.x.x.x --profile http443_gcp1_api \
  --aes-encrypt-key 0123456789ABCDEF --aes-encrypt-iv 0123456789ABCDEF \
  -C deflate --prepend-size

Stage size: 4314372 bytes
Prepend: 00 D5 41 00 (4 bytes)
IV: 30 31 32 33 ... 46 (16 bytes)
Ciphertext size: 4314352 bytes  (multiple of 16)
Decryption: successful
Decompressed size: ~10.9 MB

Failing command (newer Sliver (v1.5.39, with functions 1.6.0, current git clone repository) profiles stage):
profiles stage \
  --aes-encrypt-key 0123456789ABCDEF \
  --aes-encrypt-iv 0123456789ABCDEF \
  -c deflate --prepend-size

Stage size: 10311600 bytes
Prepend: 30 31 32 33 (4 bytes)
IV: 34 35 36 37 ... 2B (16 bytes)
Ciphertext size: 10311580 bytes  (not divisible by 16)
Decryption result:  fails with error:

Ciphertext invalid (too short or not aligned)

Decryption process used:

Read full stage from network.
Skip first 4 bytes (prepend size).
Extract next 16 bytes as IV.
Decrypt remaining bytes using AES-CBC with OpenSSL and EVP_CIPHER_CTX_set_padding(ctx, 0).
Decompress decrypted data (deflate).

Notes:

The AES key and IV are 16 bytes (128-bit).
When padding is disabled, ciphertext must be aligned to 16 bytes — the new payload is not.
With Sliver v1.5.43 (stage-listener), everything works fine.
With "newer" Sliver v1.5.39 (profiles stage), ciphertext is misaligned.

Questions:

Has the AES padding behavior changed in profiles stage?
Is padding (e.g., PKCS#7) now always enabled?
Can we disable padding and generate raw AES-CBC ciphertext (aligned to 16 bytes), as in older versions?
Thanks for your support — and for this amazing framework!

**Comment by tomaszniezbedny** [comment]
Additional notes:

- When cloning the repository via git clone https://github.com/BishopFox/sliver.git (default branch), the resulting codebase builds Sliver v1.5.39, which includes newer staging logic (profiles stage) from the upcoming v1.6.0.
- The latest tag (v1.5.43) does not build successfully — possibly due to outdated or broken dependencies — so for this test I used the compiled binaries of both versions.
- The issue therefore appears when building from the current default branch (v1.5.39), which already includes the updated staging system that seems to break compatibility with raw AES-CBC + deflate loaders.

- This debugging effort was motivated by the need to disable AMSI bypass, which is only configurable at compile time in the 1.5.x series.
- I initially intended to work exclusively with v1.5.43, where AES + deflate loaders worked correctly. However, building Sliver from source at tag v1.5.43 resulted in compilation errors, so I used precompiled binaries of that version to test AES stage decryption.
- I successfully disabled AMSI in v1.5.39, which builds correctly and includes the new staging logic (profiles stage) from upcoming v1.6.0.
- Unfortunately, while AES + deflate stages worked in v1.5.43 (stage-listener), the same decryption process fails in v1.5.39, even though it is supposedly an earlier version — because it already includes breaking changes from the v1.6.0 codebase.

Summary:
v1.5.43 works for AES+deflate, but AMSI cannot be disabled without recompiling (and source doesn't compile cleanly).
v1.5.39 compiles and allows AMSI customization, but stage format appears broken for AES-CBC w/o padding.

This mismatch complicates loader development relying on raw decryption and manual deflate handling.

**Comment by tomaszniezbedny** [comment]
The cryptography.go implementation was really helpful in figuring this out.

The decrypted stage payload structure in profiles stage differs slightly from stage-listener. In particular:
--prepend-size in profiles stage adds ASCII bytes (e.g., 30 31 32 33 for "0123"), not a 4-byte little-endian integer as expected in older versions.
As a result, if a loader assumes binary size prepending, it will misalign the IV offset, extract the wrong IV, and fail decryption with:
 "Ciphertext invalid (too short or not aligned)"

After adjusting my loader to account for the actual stage layout:
[4 bytes ASCII prepend, optional]
[16 bytes IV]
[PKCS#7-padded ciphertext (AES-CBC)]

..decryption works perfectly. No need to disable padding or change the key/IV format.
