### ISSUE TITLE
Go 1.11 doesn't support strings.ReplaceAll()

### ISSUE THREAD

**Issue by v-p-b** [BishopFox/sliver#110]
**Describe the bug**
Documentation states that minimal supported Go version is 1.11. According to https://github.com/golang/go/issues/28280 1.11 doesn't support strings.ReplaceAll(), and Sliver build fails with the following message: 

```
GOOS=darwin CGO_ENABLED=0 go build -tags netgo -ldflags '-s -w' -o sliver-server ./server
# github.com/bishopfox/sliver/server/generate
server/generate/codenames.go:87:9: undefined: strings.ReplaceAll
Makefile:28: recipe for target 'macos' failed
make: *** [macos] Error 2
```

**To Reproduce**
Follow the "From Scratch" compilation instructions of the Wiki. Error occurs on `make`. 

**Expected behavior**
Make runs without any error.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu Xenial
 - Version: Git master

**Additional context**

Nope.

**Comment by rkervella** [comment]
@moloch-- what direction should we take here? Refactor to make it work with 1.11, or update the docs?
As 1.13 should be out this august, I'd be in favor of the later.

**Comment by moloch--** [comment]
Yea, let's update the docs.

**Comment by lesnuages** [comment]
I can't see one right now, but yeah I'd like to be sure before changing the docs.

**Comment by v-p-b** [comment]
@moloch-- It was in the docs and also available in the Gophers PPA for Ubuntu. Since Go is pretty easy to install I don't think that elevating the minimum supported version would cause any trouble for users.
